# Generated by Django 3.1.2 on 2021-01-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.TextField()),
                ('certificate', models.TextField()),
                ('duration', models.TextField()),
                ('genre', models.TextField()),
                ('rating', models.TextField()),
                ('metascore', models.TextField()),
                ('description', models.TextField()),
                ('director', models.TextField()),
                ('cast', models.TextField()),
            ],
        ),
    ]
