# Generated by Django 2.0.7 on 2021-02-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='Photo Unavaliable', upload_to='images/'),
        ),
    ]
