# Generated by Django 2.1.5 on 2021-02-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_csv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv',
        ),
    ]
